# Generated by Django 5.2 on 2025-11-14 02:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contenido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=250, verbose_name='título')),
                ('sinopsis', models.TextField(blank=True, verbose_name='sinopsis')),
                ('director', models.CharField(blank=True, max_length=200, verbose_name='director')),
                ('anio', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1888), django.core.validators.MaxValueValidator(2026)], verbose_name='año')),
                ('generos', models.JSONField(blank=True, default=list, verbose_name='géneros')),
                ('productora', models.CharField(blank=True, max_length=200, verbose_name='productora')),
                ('imagen_portada', models.ImageField(blank=True, null=True, upload_to='portadas/', verbose_name='imagen de portada')),
                ('tipo', models.CharField(choices=[('pelicula', 'Película'), ('serie', 'Serie')], default='pelicula', max_length=10, verbose_name='tipo')),
                ('capitulos', models.PositiveIntegerField(blank=True, help_text='Número de capítulos (solo para series)', null=True, verbose_name='capítulos')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('actualizado', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
            ],
            options={
                'verbose_name': 'contenido',
                'verbose_name_plural': 'contenidos',
                'ordering': ['-anio', 'titulo'],
            },
        ),
    ]
